class BaseAgent:
    """
    Abstract base class that defines the interface for all agents.
    """
    
    def __init__(self, llm, system_prompt, name, verbose=False):
        """
        Constructor that initializes agent properties.
        
        Args:
            llm: Language model instance used by the agent.
            system_prompt: Instructions that guide agent behavior.
            name: String identifier for the agent.
            verbose: Boolean flag for detailed logging.
        """
        self.llm = llm
        self.system_prompt = system_prompt
        self.name = name
        self.verbose = verbose
        
    def run(self, user_query):
        """
        Abstract method that processes a user query and returns a response.
        
        Args:
            user_query: The query to be processed by the agent.
            
        Returns:
            Response generated by the agent.
        """
        raise NotImplementedError("Subclasses must implement this method")