from src.repository.agent.tool_call_agent import ToolCallAgent

class GeneralAgent(ToolCallAgent):
    """
    Main implementation of general-purpose agent with memory and advanced features.
    """
    
    def __init__(self, llm, tools, system_prompt=None, name="GeneralAgent", verbose=False, max_iterations=5, memory_enabled=True):
        """
        Constructor for Memory agent.
        
        Args:
            llm: Language model instance used by the agent.
            tools: List of BaseTool instances available to the agent.
            system_prompt: Instructions that guide agent behavior. If None, uses default.
            name: String identifier for the agent.
            verbose: Boolean flag for detailed logging.
            max_iterations: Maximum tool calling iterations before stopping.
            memory_enabled: Boolean controlling conversation history tracking.
        """
        if system_prompt is None:
            system_prompt = self._get_default_system_prompt()
        
        super().__init__(llm, tools, system_prompt, name, verbose, max_iterations)
        self.memory_enabled = memory_enabled
        self.conversation_history = [] if memory_enabled else None
    
    def run(self, user_query, context=None):
        """
        Processes queries with conversation history as context.
        
        Args:
            user_query: The query to be processed by the agent.
            context: Optional context (e.g., conversation history) to use for the query.
            
        Returns:
            Response generated by the agent after potentially using tools.
        """
        if self.memory_enabled:
            if context is None:
                context = self.conversation_history
            if context is not None:
                self.conversation_history = context
        # Delegate to ToolCallAgent's run method, passing user_query (and context if needed)
        # Here, we assume ToolCallAgent.run can be extended to use context if required
        response = super().run(user_query)
        if self.memory_enabled and self.conversation_history is not None:
            self.conversation_history.append({"user": user_query, "response": response})
        return response
    
    def _get_default_system_prompt(self):
        """
        Returns default system instructions.
        
        Returns:
            String containing default system prompt.
        """
        # Implementation will return a well-crafted default system prompt
        pass